'use strict';
const $=s=>document.querySelector(s);const modules=[
 {id:'sub',icon:'●',name:'Hızlı miktar',desc:'Kısa gösterilen noktaları tek tek saymadan tanı.'},
 {id:'compare',icon:'≶',name:'Sayı–çoğunluk',desc:'Nokta miktarı sayıya göre daha çok, aynı veya daha az.'},
 {id:'congruent',icon:'◎',name:'Uyumlu–uyumsuz',desc:'Sayı ile miktarın eşleşip eşleşmediğine karar ver.'},
 {id:'dual',icon:'🥁',name:'Miktar + ses',desc:'Görsel kararı verirken dört davulu üst üste izle.'},
 {id:'chase',icon:'🦊',name:'Kim kimi kovalar?',desc:'İki hayvanı karşılaştır, avcı–av ilişkisini seç.'},
 {id:'previous',icon:'↩',name:'Öndeki arkadakini avlar mı?',desc:'Bir önceki hayvanı akılda tutarak karar ver.'},
 {id:'source',icon:'♫',name:'Özgün sayı akışı',desc:'Yüklediğiniz 60 uyaran ve 7:04 ses kaydıyla çalışma.'}
];
const animals=['fly','duck','frog','cat','mouse','fox','stork'];
const prey={fly:[],duck:['fly'],frog:['fly'],cat:['mouse','duck'],mouse:[],fox:['mouse','duck'],stork:['frog','fly']};
let mode='sub',state=null,sourceData=window.SOURCE60||[],ctx=null,drumTimer=null,raf=null,hideTimer=null,nextTimer=null;
const audio=$('#sourceAudio');
function rnd(n){return Math.floor(Math.random()*n)}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function moduleUI(){const box=$('#modules');box.innerHTML='';modules.forEach(m=>{let b=document.createElement('button');b.className='module'+(m.id===mode?' active':'');b.innerHTML=`<span>${m.icon}</span><strong>${m.name}</strong><small>${m.desc}</small>`;b.onclick=()=>{mode=m.id;moduleUI();note()};box.append(b)})}
function note(){$('#modeNote').textContent=mode==='source'?'Özgün bölüm: 60 görsel, her biri 7,06 saniye. Yüklenen kayıt, Başlat düğmesine dokununca aynı anda açılır. Bu bölümde miktarlar subitizing sınırının üzerindedir.':mode==='dual'?'Davul sesleri uygulamada üretilir. Dört davul üst üste geldiğinde ayrı ses düğmesine basılır.':'Düzey ve süre ayarlarını öğrencinin performansına göre seçin.'}
moduleUI();note();

if('serviceWorker' in navigator && location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
$('#soundTest').onclick=()=>tone('drum');
function tone(kind){try{ctx=ctx||new (window.AudioContext||window.webkitAudioContext)();ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=kind==='drum'?'triangle':'sine';osc.frequency.setValueAtTime(kind==='drum'?145:kind==='bell'?650:410,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(kind==='drum'?65:kind==='bell'?530:330,ctx.currentTime+.13);gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.22,ctx.currentTime+.006);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.22);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.24)}catch(e){}}
function config(){return {student:$('#student').value.trim(),level:+$('#level').value,rounds:+$('#rounds').value,exposure:+$('#exposure').value}}
function makeTrials(m,c){let a=[];const max=c.level===1?4:c.level===2?6:(m==='sub'?6:9);let previous=null;
 for(let i=0;i<c.rounds;i++){
  if(m==='sub'){let n=1+rnd(max);a.push({kind:'sub',count:n,correct:String(n)})}
  else if(['compare','congruent','dual'].includes(m)){let n=1+rnd(max),d=[-2,-1,0,1,2][rnd(5)],count=Math.max(1,Math.min(max,n+d));if(i%3===0)count=n;let key=count>n?'Daha çok':count<n?'Daha az':'Aynı';a.push({kind:'compare',number:n,count,correct:m==='congruent'?(count===n?'Uyumlu':'Uyumsuz'):key})}
  else if(m==='chase'){let hunter=animals[rnd(animals.length)],target=animals[rnd(animals.length)];if(i%2===0){hunter=['frog','cat','fox','stork'][rnd(4)];target=prey[hunter][rnd(prey[hunter].length)]}a.push({kind:'chase',hunter,target,correct:prey[hunter].includes(target)?'Evet':'Hayır'})}
  else if(m==='previous'){let animal=animals[rnd(animals.length)];if(i>0&&i%2===0&&prey[previous].length)animal=prey[previous][rnd(prey[previous].length)];a.push({kind:'previous',animal,prior:previous,correct:previous&&prey[previous].includes(animal)?'Evet':'Hayır'});previous=animal}
 }
 return a}
$('#start').onclick=async()=>{const c=config();if(mode==='source'&&!sourceData.length){$('#modeNote').textContent='Kaynak veriler yüklenmedi. Uygulamayı ZIP içindeki klasörle birlikte açın.';return}
 clearAll();try{ctx=ctx||new (window.AudioContext||window.webkitAudioContext)();await ctx.resume()}catch(e){}
 state={mode,config:c,trials:mode==='source'?sourceData.map(x=>({...x,kind:'source',correct:x.count>x.number?'Daha çok':x.count<x.number?'Daha az':'Aynı'})):makeTrials(mode,c),index:0,answers:[],started:performance.now(),paused:false,sound:{targets:0,hits:0,false:0,misses:0,pending:false,streak:0},lastSound:'',trialStart:0,sourceStart:0};
 $('#setup').classList.add('hidden');$('#summary').classList.add('hidden');$('#play').classList.remove('hidden');$('#moduleName').textContent=modules.find(x=>x.id===mode).name;$('#dual').classList.toggle('hidden',mode!=='dual'&&mode!=='source');$('#audioHint').textContent=mode==='source'?'Dört davul sesi art arda duyduğunda bas.':'Aynı davulu dört kez art arda duyunca bas.';$('#pause').textContent='Duraklat';
 if(mode==='source'){try{audio.currentTime=0;await audio.play()}catch(e){$('#feedback').textContent='Ses otomatik başlamadı. Sesi dene düğmesine basıp tekrar başlatın.'}state.sourceStart=performance.now();sourceLoop()}else{showTrial();if(mode==='dual')startDrums()}
};
function clearAll(){clearTimeout(hideTimer);clearTimeout(nextTimer);clearInterval(drumTimer);cancelAnimationFrame(raf);audio.pause()}
function points(n,sourcePts){let positions=sourcePts?sourcePts.map(p=>({x:18+(p.x-.15)*95,y:12+(p.y-.12)*100})):Array.from({length:n},(_,i)=>{let cols=Math.ceil(Math.sqrt(n)),rows=Math.ceil(n/cols),col=i%cols,row=Math.floor(i/cols);return{x:20+(col+.5)*60/cols+(rnd(9)-4),y:18+(row+.5)*65/rows+(rnd(9)-4)}});
 return `<div class="dotfield">${positions.slice(0,n).map(p=>`<i class="dot" style="left:${Math.max(8,Math.min(92,p.x))}%;top:${Math.max(8,Math.min(92,p.y))}%"></i>`).join('')}</div>`}
function img(n){return `<img src="assets/${n}.png" alt="${n}">`}
function render(t){if(t.kind==='sub')return points(t.count);if(t.kind==='compare'||t.kind==='source')return `<div class="compare"><div class="numeral">${t.number}</div><div>${points(t.count,t.points)}</div><span class="divider"></span></div>`;if(t.kind==='chase')return `<div class="animalpair">${img(t.hunter)}<span class="arrow">→</span>${img(t.target)}</div>`;return `<div class="animalone">${img(t.animal)}</div>`}
function labels(t){if(state.mode==='sub')return Array.from({length:state.config.level===1?4:state.config.level===2?6:9},(_,i)=>String(i+1));if(state.mode==='congruent')return ['Uyumlu','Uyumsuz'];if(['chase','previous'].includes(state.mode))return ['Evet','Hayır'];return ['Daha çok','Aynı','Daha az']}
function showTrial(){if(!state||state.paused)return;if(state.index>=state.trials.length){end();return}let t=state.trials[state.index];state.trialStart=performance.now();$('#counter').textContent=`${state.index+1} / ${state.trials.length}`;$('#progressBar').style.width=`${state.index/state.trials.length*100}%`;
 $('#instruction').textContent=t.kind==='sub'?'Kaç nokta gördün?':t.kind==='previous'?(state.index===0?'İlk hayvanı aklında tut.':'Önceki hayvan bu hayvanı avlar mı?'):t.kind==='chase'?'Soldaki hayvan sağdakini avlar mı?':state.mode==='congruent'?'Sayı ve miktar uyumlu mu?':'Noktalar sayıdan daha çok mu, aynı mı, daha az mı?';
 $('#stage').innerHTML=render(t);$('#feedback').textContent='';$('#choices').innerHTML='';
 if(t.kind==='previous'&&state.index===0){nextTimer=setTimeout(()=>record('Başlangıç',true),2200);return}
 for(const label of labels(t)){let b=document.createElement('button');b.textContent=label;b.onclick=()=>record(label,false);$('#choices').append(b)}
 if(t.kind==='sub')hideTimer=setTimeout(()=>{$('#stage').innerHTML='<div class="mask">● ● ●<br><small>Kaç noktaydı?</small></div>'},state.config.exposure)
}
function record(answer,intro){if(!state||state.paused)return;let t=state.trials[state.index];if(!t||state.answers.some(a=>a.index===state.index))return;const rt=Math.round(performance.now()-state.trialStart);state.answers.push({index:state.index,answer,correct:t.correct,ok:intro||answer===t.correct,rt,mode:state.mode});$('#feedback').textContent=intro?'Şimdi başlıyor.':answer===t.correct?'Doğru':'Bir sonraki denemeye geç.';$('#choices').innerHTML='';clearTimeout(hideTimer);nextTimer=setTimeout(()=>{state.index++;showTrial()},350)}
function sourceLoop(){if(!state||state.mode!=='source'||state.paused)return;let index=Math.min(59,Math.floor(audio.currentTime/7.06));if(index!==state.index||!state.trialStart){state.index=index;let t=state.trials[index];state.trialStart=performance.now();$('#counter').textContent=`${index+1} / 60`;$('#progressBar').style.width=`${index/60*100}%`;$('#instruction').textContent='Nokta miktarı sayıya göre nasıl?';$('#stage').innerHTML=render(t);$('#choices').innerHTML='';for(const label of labels(t)){let b=document.createElement('button');b.textContent=label;b.onclick=()=>{if(state.answers.some(a=>a.index===index))return;state.answers.push({index,answer:label,correct:t.correct,ok:label===t.correct,rt:Math.round(performance.now()-state.trialStart),mode:'source'});$('#choices').innerHTML=''};$('#choices').append(b)}}
 if(audio.ended||audio.currentTime>=audio.duration-.15){end();return}raf=requestAnimationFrame(sourceLoop)}
function startDrums(){let sequence=0;drumTimer=setInterval(()=>{if(!state||state.paused||state.mode!=='dual')return;let choice=(sequence%13>=8&&sequence%13<=11)?'drum':['drum','bell','click'][rnd(3)];sequence++;tone(choice);let s=state.sound;if(choice==='drum')s.streak++;else{s.streak=0;if(s.pending){s.misses++;s.pending=false}}if(s.streak===4){s.targets++;s.pending=true;setTimeout(()=>{if(state&&s.pending){s.misses++;s.pending=false}},1750)}if(s.streak>4)s.streak=0},1100)}
$('#soundAnswer').onclick=()=>{if(!state||state.paused)return;let s=state.sound;if(state.mode==='source'){s.hits++;$('#feedback').textContent='Ses işareti kaydedildi.';return}if(s.pending){s.hits++;s.pending=false;$('#feedback').textContent='Davul dizisini yakaladın.'}else{s.false++;$('#feedback').textContent='Ses işaretini kontrol et.'}};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&state&&['dual','source'].includes(state.mode)&&!$('#play').classList.contains('hidden')){e.preventDefault();$('#soundAnswer').click()}});
$('#pause').onclick=()=>{if(!state)return;if(state.mode==='source'){if(state.paused){state.paused=false;audio.play().then(sourceLoop).catch(()=>{});$('#pause').textContent='Duraklat'}else{state.paused=true;audio.pause();cancelAnimationFrame(raf);$('#pause').textContent='Devam et'}}else{state.paused=!state.paused;if(state.paused){clearTimeout(hideTimer);clearTimeout(nextTimer);$('#pause').textContent='Devam et';$('#feedback').textContent='Duraklatıldı'}else{$('#pause').textContent='Duraklat';if(state.answers.some(a=>a.index===state.index)){state.index++;showTrial()}else showTrial()}}};
$('#finish').onclick=end;
function end(){if(!state)return;clearAll();if(state.sound.pending){state.sound.misses++;state.sound.pending=false}let s=state;if(s.mode==='source')s.sound.targets=21;let attempted=s.answers.filter(a=>a.answer!=='Başlangıç'),correct=attempted.filter(a=>a.ok).length,missed=Math.max(0,s.trials.length-(s.mode==='previous'?1:0)-attempted.length),avg=attempted.length?Math.round(attempted.reduce((a,x)=>a+x.rt,0)/attempted.length):0;
 $('#play').classList.add('hidden');$('#summary').classList.remove('hidden');$('#summaryTitle').textContent=`${modules.find(m=>m.id===s.mode).name} tamamlandı`;
 $('#stats').innerHTML=`<div><strong>${correct}/${attempted.length}</strong><span>Doğru / yanıtlanan</span></div><div><strong>${missed}</strong><span>Atlanan</span></div><div><strong>${avg} ms</strong><span>Ortalama yanıt süresi</span></div><div><strong>${s.sound.hits}/${s.sound.targets}</strong><span>${s.mode==='source'?'Ses işareti / kaynak hedefi':'Ses hedefi'}</span></div>`;
 $('#summaryDetail').textContent=s.mode==='source'?`Yanlış görsel karar: ${attempted.length-correct}. Ses işareti: ${s.sound.hits}; kaynak yönergede 21 davul hedefi belirtilir. Ses doğruluğunu kayıtla birlikte öğretmen değerlendirmelidir.`:`Yanlış görsel karar: ${attempted.length-correct}. Yanlış ses işareti: ${s.sound.false}. Ses hedefi kaçırma: ${s.sound.misses}. Bu kayıt norm puanı değildir.`;
 try{localStorage.setItem('miktar-son-oturum',JSON.stringify({date:new Date().toISOString(),mode:s.mode,correct,attempted:attempted.length,missed,avg}))}catch(e){} }
$('#download').onclick=()=>{if(!state)return;let header='ogrenci,tarih,mod,deneme,yanit,dogru_yanit,dogruluk,tepki_ms\n',name=state.config.student.replaceAll('"','""'),date=new Date().toISOString();let rows=state.answers.filter(a=>a.answer!=='Başlangıç').map(a=>`"${name}",${date},${state.mode},${a.index+1},"${a.answer}","${a.correct}",${a.ok?1:0},${a.rt}`).join('\n');let blob=new Blob(['\ufeff'+header+rows],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='subitizing-oturum.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)};
$('#restart').onclick=()=>{state=null;$('#summary').classList.add('hidden');$('#setup').classList.remove('hidden')};
